### ISSUE TITLE
Cleanup on item eviction?

### ISSUE THREAD

**Issue by lifenautjoe** [platelk/dcache#6]
Is there a way to run some cleanup code specific to the evicted item?

Cheers,
Joel

**Comment by platelk** [comment]
Hi !

For the moment there is no by default way, but you can extends or create a storage and do it a this moment

I will take back the library and add more lifecycle trigger I think

**Comment by platelk** [comment]
Hi !

Thx to @mikes222 this item has been done in [v0.3.0](https://pub.dev/packages/dcache/versions/0.3.0)
