### ISSUE TITLE
flutter packages get error

### ISSUE THREAD

**Issue by zuiwuchang** [platelk/dcache#7]
i run `flutter packages get` have depends error
```
Because every version of flutter_test from sdk depends on meta 1.1.6 and dcache >=0.2.0 
depends on meta ^1.1.7, flutter_test from sdk is incompatible with dcache >=0.2.0.
```

**Comment by platelk** [comment]
Hi !

Thank you for this issue and the solution to solve it, in [0.2.1](https://pub.dartlang.org/packages/dcache/versions/0.2.1) I reduced the requirements on this package
